climate:
  -
    room: Schlafzimmer
    week: Mo-So
    from: "8.00"
    to: "20.00"
    temperature: 22.5
    typ: measure
    timeout: 15
  -
    room: Schlafzimmer
    week: Mo-So
    from: "20.00"
    to: "8.00"
    temperature: 21.0
    typ: set

energy:
  -
    name: Steckdose1
    on: "8.00"
    off: "18.00"
    reactivate: 60
